replicaCount: 1

image:
  repository: nginxdemos/hello
  tag: latest
  pullPolicy: IfNotPresent


service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

livenessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 3
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 3
  periodSeconds: 10

serviceAccount:
  create: false

ingress:
  enabled: false

autoscaling:
  enabled: false
