apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service
  namespace: app
  labels:
    app.kubernetes.io/name: data-service
    app.kubernetes.io/instance: data-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: data-service
      app.kubernetes.io/instance: data-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: data-service
        app.kubernetes.io/instance: data-service
    spec:
      containers:
      - name: data-service
        image: hashicorp/http-echo
        args:
          - "-text=Hello from data-service"
        ports:
          - containerPort: 5678
            name: http
        livenessProbe:
          httpGet:
            path: /
            port: 5678
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 5678
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi

