apiVersion: v1
kind: Service
metadata:
  name: data-service
  namespace: app
  labels:
    app.kubernetes.io/name: data-service
    app.kubernetes.io/instance: data-service
spec:
  ports:
  - port: 5678
    targetPort: 5678
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: data-service
    app.kubernetes.io/instance: data-service
  type: ClusterIP

