apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-data-sa
  namespace: app
subjects:
- kind: ServiceAccount
  name: data-sa
  namespace: app
roleRef:
  kind: Role
  name: s3-access-role
  apiGroup: rbac.authorization.k8s.io

