apiVersion: v1
kind: Pod
metadata:
  name: data-test
  namespace: app
spec:
  serviceAccountName: data-sa
  containers:
  - name: curl
    image: curlimages/curl
    command: ["sh", "-c", "curl -u $MINIO_ACCESS_KEY:$MINIO_SECRET_KEY http://minio.minio.svc.cluster.local:9000/minio/health/live"]
    envFrom:
    - secretRef:
        name: minio-credentials
  restartPolicy: Never

