apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: app
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/instance: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: auth-service
      app.kubernetes.io/instance: auth-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: auth-service
        app.kubernetes.io/instance: auth-service
    spec:
      serviceAccountName: auth-service
      containers:
      - name: auth-service
        image: curlimages/curl:7.85.0
        command:
          - /bin/sh
          - -c
          - |
            # simulate a safe request without logging Authorization header
            while true; do
              curl -s http://httpbin.org/get
              sleep 15
            done
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 256Mi
      restartPolicy: Always