apiVersion: v1
kind: Pod
metadata:
  name: minio-mc
  namespace: app
spec:
  serviceAccountName: data-sa
  containers:
  - name: mc
    image: minio/mc
    command: ["sleep", "3600"]
  restartPolicy: Never

